FROM centos:latest
RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
RUN yum install -y httpd epel-release python3-setuptools crontabs
RUN yum install -y certbot mod_ssl
RUN easy_install-3.6 supervisor
RUN yum update -y
RUN echo "LISTEN 443" >> /etc/httpd/conf/httpd.conf && echo "IncludeOptional conf-ssl.d/*.conf" >> /etc/httpd/conf/httpd.conf
RUN echo "30 2 * * * /usr/bin/python3 /root/check.py" >> /var/spool/cron/root
RUN chmod 600 /var/spool/cron/root
COPY config/supervisord.conf /usr/local/supervisord.conf
COPY python_check/check.py /root/check.py
EXPOSE 80
EXPOSE 443
CMD ["supervisord", "-c", "/usr/local/supervisord.conf"]